namespace DatabaseViewer.Core.Models;

public sealed class ColumnSchema
{
    public string Name { get; set; } = string.Empty;

    public string DataType { get; set; } = string.Empty;

    public string? Comment { get; set; }

    public int? NumericPrecision { get; set; }

    public int? NumericScale { get; set; }

    public bool IsPrimaryKey { get; set; }

    public bool IsNullable { get; set; }

    public bool IsAutoGenerated { get; set; }

    public bool IsComputed { get; set; }

    public int? MaxLength { get; set; }

    public ForeignKeyReference? ForeignKey { get; set; }
}