namespace DatabaseViewer.Core.Models;

public sealed class ColumnSchema
{
    public string Name { get; set; } = string.Empty;

    public string DataType { get; set; } = string.Empty;

    public string? Comment { get; set; }

    public int? NumericPrecision { get; set; }

    public int? NumericScale { get; set; }

    public bool IsPrimaryKey { get; set; }

    public bool IsNullable { get; set; }

    public bool IsAutoGenerated { get; set; }

    public bool IsComputed { get; set; }

    public int? MaxLength { get; set; }

    /// <summary>标记该列为 SQLite 隐式 rowid 列（表本身没有显式主键时注入）。</summary>
    public bool IsHiddenRowId { get; set; }

    public ForeignKeyReference? ForeignKey { get; set; }
}