export type ProviderType = 'sqlserver' | 'mysql' | 'postgresql'
export type AuthenticationMode = 'windows' | 'password'
export type CellValue = string | number | boolean | null

export interface ConnectionInfo {
  id: string
  name: string
  provider: ProviderType
  host: string
  port?: number
  authentication: AuthenticationMode
  accent: string
  error?: string | null
  databases: DatabaseInfo[]
}

export interface CreateConnectionRequest {
  name: string
  provider: ProviderType
  authentication: AuthenticationMode
  host: string
  port?: number | null
  username?: string | null
  password?: string | null
  trustServerCertificate: boolean
}

export interface DatabaseInfo {
  name: string
  tables: TableSummary[]
}

export interface DatabaseGraphNode {
  tableKey: string
  title: string
  rowCount?: number | null
  isJunction: boolean
  comment?: string | null
  columns: DatabaseGraphColumn[]
}

export interface DatabaseGraphColumn {
  name: string
  type: string
  displayType: string
  isNullable: boolean
  isPrimaryKey: boolean
  isForeignKey: boolean
}

export interface DatabaseGraphEdge {
  sourceTableKey: string
  targetTableKey: string
  relationType: 'one-to-one' | 'many-to-one' | 'many-to-many'
  label: string
  logical: boolean
  viaTableKey?: string | null
  sourceColumn: string
  targetColumn: string
}

export interface DatabaseGraph {
  connectionId: string
  database: string
  nodes: DatabaseGraphNode[]
  edges: DatabaseGraphEdge[]
}

export interface TableColumn {
  name: string
  type: string
  isPrimaryKey?: boolean
  isNullable?: boolean
  isAutoGenerated?: boolean
  isComputed?: boolean
  maxLength?: number | null
}

export interface ForeignKeyRef {
  sourceColumn: string
  targetTableKey: string
  targetColumn: string
  logical: boolean
}

export interface TableRow {
  rowKey: string
  [key: string]: CellValue
}

export interface TableSummary {
  key: string
  database: string
  schema?: string
  name: string
  comment?: string
  rowCount?: number | null
}

export interface TableDefinition extends TableSummary {
  primaryKeys: string[]
  columns: TableColumn[]
  foreignKeys: ForeignKeyRef[]
  rows: TableRow[]
  hasMoreRows: boolean
  rowsLoaded?: boolean
}

export interface TableSearchResponse {
  tableKey: string
  query: string
  columns: string[]
  rows: TableRow[]
  totalMatches: number
  hasMoreRows: boolean
}

export interface SqlResultColumn {
  name: string
  type: string
}

export interface SqlResultRow {
  [key: string]: CellValue
}

export interface SqlResultSet {
  name: string
  columns: SqlResultColumn[]
  rows: SqlResultRow[]
  rowCount: number
  truncated: boolean
}

export interface SqlExecutionResponse {
  connectionId: string
  database: string
  executedSql: string
  affectedRows?: number | null
  elapsedMs: number
  resultSets: SqlResultSet[]
}

export interface SqlContextTable {
  name: string
  schema?: string | null
  qualifiedName: string
  columns: string[]
}

export interface SqlContext {
  connectionId: string
  database: string
  provider: ProviderType
  tables: SqlContextTable[]
}

export interface ExplorerGridPanel {
  id: string
  type: 'grid'
  tableKey: string
}

export interface ExplorerDetailPanel {
  id: string
  type: 'detail'
  tableKey: string
  rowKey: string
  depth: number
  sourceLabel: string
}

export type ExplorerPanel = ExplorerGridPanel | ExplorerDetailPanel

export interface TableWorkspaceTab {
  id: string
  type: 'table'
  tableKey: string
  detailPanels: ExplorerDetailPanel[]
}

export interface SqlWorkspaceTab {
  id: string
  type: 'sql'
  connectionId: string | null
  database: string | null
  sqlText: string
  loading: boolean
  error: string | null
  result: SqlExecutionResponse | null
  selectedResultIndex: number
}

export interface GraphWorkspaceTab {
  id: string
  type: 'graph'
  connectionId: string
  database: string
  loading: boolean
  error: string | null
  graph: DatabaseGraph | null
}

export type WorkspaceTab = TableWorkspaceTab | SqlWorkspaceTab | GraphWorkspaceTab

export interface ReverseReferenceRow {
  rowKey: string
  values: TableRow
}

export interface ReverseReferenceGroup {
  sourceTableKey: string
  relationLabel: string
  rows: ReverseReferenceRow[]
}

export interface RecordDetail {
  tableKey: string
  rowKey: string
  row: TableRow
  primaryKeys: string[]
  columns: TableColumn[]
  foreignKeys: ForeignKeyRef[]
  reverseReferences: ReverseReferenceGroup[]
}

export interface ForeignKeyTarget {
  targetTableKey: string
  targetRowKey: string
  sourceLabel: string
}

export interface CellContentPreview {
  tableKey: string
  rowKey: string
  columnName: string
  kind: 'image' | 'text' | 'binary' | 'empty'
  mimeType: string
  suggestedFileName: string
  sizeBytes: number
  textContent?: string | null
  base64Data?: string | null
}

export interface TableCellUpdateRequest {
  tableKey: string
  rowKey: string
  columnName: string
  valueKind: 'text' | 'binary' | 'null'
  textValue?: string | null
  base64Value?: string | null
  setNull: boolean
}

export interface TableCellUpdateResponse {
  tableKey: string
  previousRowKey: string
  rowKey: string
  row: TableRow
}