<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { NAlert, NButton, NCard, NEmpty, NModal, NSpin, NTooltip } from 'naive-ui'
import GridCellEditorModal from './GridCellEditorModal.vue'
import { useExplorerStore } from '../stores/explorer'
import type { CellContentPreview, CellValue, ForeignKeyRef, TableColumn, TableRow } from '../types/explorer'

const props = defineProps<{ tableKey: string }>()
const store = useExplorerStore()

const table = computed(() => store.getLoadedTable(props.tableKey))
const tableMeta = computed(() => store.getTable(props.tableKey))
const rows = computed(() => store.getFilteredRows(props.tableKey))
const searchState = computed(() => store.getTableSearchState(props.tableKey))
const searchActive = computed(() => store.isSearchActive(props.tableKey))
const sortState = computed(() => store.getTableSortState(props.tableKey))
const columnWidths = ref<Record<string, number>>({})
const previewCache = ref<Record<string, CellContentPreview>>({})
const previewState = ref<{
  show: boolean
  loading: boolean
  title: string
  content: CellContentPreview | null
  error: string | null
}>({
  show: false,
  loading: false,
  title: '',
  content: null,
  error: null,
})
type VisibleColumn = TableColumn & { fk?: ForeignKeyRef }

const contextMenu = ref<{
  show: boolean
  x: number
  y: number
  rowKey: string
  column: VisibleColumn
  value: CellValue | undefined
} | null>(null)
const editorState = ref<{
  show: boolean
  rowKey: string | null
  column: VisibleColumn | null
  foreignKey: ForeignKeyRef | null
  value: CellValue | undefined
  saving: boolean
}>({
  show: false,
  rowKey: null,
  column: null,
  foreignKey: null,
  value: undefined,
  saving: false,
})

function isBinaryColumn(columnName: string, columnType?: string) {
  const normalizedType = (columnType ?? '').toLowerCase()
  const normalizedName = columnName.toLowerCase()
  return normalizedType.includes('binary')
    || normalizedType.includes('image')
    || normalizedType.includes('blob')
    || normalizedName.endsWith('image')
    || normalizedName.endsWith('photo')
    || normalizedName.endsWith('thumbnail')
}

const visibleColumns = computed<VisibleColumn[]>(() => {
  if (!table.value) {
    return []
  }

  return table.value.columns.map((column) => {
    const fk = store.getForeignKey(props.tableKey, column.name)
    return {
      ...column,
      isPrimaryKey: !!column.isPrimaryKey,
      fk,
    }
  })
})

const hasPrimaryKeyColumns = computed(() => visibleColumns.value.some((column) => column.isPrimaryKey))

function cellValue(row: TableRow, columnName: string, columnType: string | undefined) {
  return store.formatFieldValue(columnName, columnType, row[columnName] ?? null)
}

function displayColumnType(column: TableColumn) {
  if (!column.type) {
    return 'unknown'
  }

  if (column.maxLength === null || column.maxLength === undefined) {
    return column.type
  }

  if (column.maxLength < 0) {
    return `${column.type}(max)`
  }

  return `${column.type}(${column.maxLength})`
}

function handleRowOpen(rowKey: string) {
  store.openRowFromGrid(props.tableKey, rowKey)
}

function handleForeignKeyClick(rowKey: string, sourceColumn: string) {
  const foreignKey = store.getForeignKey(props.tableKey, sourceColumn)
  if (!foreignKey) {
    return
  }

  store.navigateForeignKeyFromGrid(props.tableKey, rowKey, foreignKey)
}

function isReadOnlySystemColumn(columnType: string | undefined) {
  const normalized = (columnType ?? '').toLowerCase()
  return normalized === 'timestamp' || normalized === 'rowversion'
}

function isEditableColumn(column: VisibleColumn) {
  return !!table.value?.primaryKeys.length
    && !column.isAutoGenerated
    && !column.isComputed
    && !isReadOnlySystemColumn(column.type)
}

function isRowOpenCell(columnName: string, columnType: string | undefined, isPrimaryKey: boolean | undefined, columnIndex: number) {
  if (isPrimaryKey) {
    return true
  }

  if (hasPrimaryKeyColumns.value) {
    return false
  }

  return columnIndex === 0 && !isBinaryColumn(columnName, columnType)
}

function sortIndicator(columnName: string) {
  if (sortState.value.columnName !== columnName) {
    return ''
  }

  return sortState.value.direction === 'asc'
    ? '↑'
    : sortState.value.direction === 'desc'
      ? '↓'
      : ''
}

function handleHeaderSort(columnName: string, columnType: string | undefined) {
  void store.toggleTableSort(props.tableKey, columnName, columnType)
}

const hasRows = computed(() => rows.value.length > 0)
const loadedRowCount = computed(() => searchActive.value ? (searchState.value?.rows.length ?? 0) : (table.value?.rows.length ?? 0))
const totalRowCount = computed(() => searchActive.value ? (searchState.value?.totalMatches ?? 0) : (tableMeta.value?.rowCount ?? loadedRowCount.value))
const hasMoreRows = computed(() => searchActive.value ? !!searchState.value?.hasMoreRows : !!table.value?.hasMoreRows)

const previewImageUrl = computed(() => {
  const content = previewState.value.content
  if (!content?.base64Data || content.kind !== 'image') {
    return null
  }

  return `data:${content.mimeType};base64,${content.base64Data}`
})

function columnStyle(columnName: string) {
  const width = columnWidths.value[columnName]
  if (!width) {
    return undefined
  }

  return {
    width: `${width}px`,
    minWidth: `${width}px`,
    maxWidth: `${width}px`,
  }
}

function beginResize(event: MouseEvent, columnName: string) {
  event.preventDefault()
  event.stopPropagation()

  const header = (event.currentTarget as HTMLElement).closest('th')
  const startWidth = header?.getBoundingClientRect().width ?? columnWidths.value[columnName] ?? 120
  const startX = event.clientX

  const onMouseMove = (moveEvent: MouseEvent) => {
    const nextWidth = Math.max(56, startWidth + moveEvent.clientX - startX)
    columnWidths.value = {
      ...columnWidths.value,
      [columnName]: nextWidth,
    }
  }

  const onMouseUp = () => {
    window.removeEventListener('mousemove', onMouseMove)
    window.removeEventListener('mouseup', onMouseUp)
  }

  window.addEventListener('mousemove', onMouseMove)
  window.addEventListener('mouseup', onMouseUp)
}

function resetColumnWidth(columnName: string) {
  const next = { ...columnWidths.value }
  delete next[columnName]
  columnWidths.value = next
}

function previewCacheKey(rowKey: string, columnName: string) {
  return `${rowKey}::${columnName}`
}

async function ensureCellContent(rowKey: string, columnName: string) {
  const key = previewCacheKey(rowKey, columnName)
  if (previewCache.value[key]) {
    return previewCache.value[key]
  }

  const content = await store.fetchCellContent(props.tableKey, rowKey, columnName)
  previewCache.value = {
    ...previewCache.value,
    [key]: content,
  }
  return content
}

async function openBinaryPreview(rowKey: string, columnName: string) {
  try {
    const content = await ensureCellContent(rowKey, columnName)
    if (content.kind === 'empty' || content.sizeBytes === 0) {
      return
    }

    previewState.value = {
      show: true,
      loading: false,
      title: `${tableMeta.value?.name ?? props.tableKey}.${columnName}`,
      content,
      error: null,
    }
  }
  catch (error) {
    previewState.value = {
      show: true,
      loading: false,
      title: `${tableMeta.value?.name ?? props.tableKey}.${columnName}`,
      content: null,
      error: error instanceof Error ? error.message : '二进制内容读取失败',
    }
  }
}

function closeContextMenu() {
  contextMenu.value = null
}

function openCellContextMenu(event: MouseEvent, rowKey: string, column: VisibleColumn, value: CellValue | undefined) {
  contextMenu.value = {
    show: true,
    x: event.clientX,
    y: event.clientY,
    rowKey,
    column,
    value,
  }
}

function handlePrimaryCellDoubleClick(event: MouseEvent, rowKey: string) {
  event.preventDefault()
  event.stopPropagation()
  handleRowOpen(rowKey)
}

function openCellEditor(rowKey: string, column: VisibleColumn, value: CellValue | undefined) {
  if (!isEditableColumn(column)) {
    return
  }

  closeContextMenu()
  editorState.value = {
    show: true,
    rowKey,
    column,
    foreignKey: column.fk ?? null,
    value,
    saving: false,
  }
}

function handleCellDoubleClick(event: MouseEvent, rowKey: string, column: VisibleColumn, columnIndex: number, value: CellValue | undefined) {
  if (column.fk || isBinaryColumn(column.name, column.type) || isRowOpenCell(column.name, column.type, column.isPrimaryKey, columnIndex)) {
    return
  }

  event.preventDefault()
  event.stopPropagation()
  openCellEditor(rowKey, column, value)
}

function handleCellMouseDown(event: MouseEvent, suppressSelection: boolean) {
  if (suppressSelection && event.detail > 1) {
    event.preventDefault()
  }
}

function handleBinaryCellClick(event: MouseEvent, rowKey: string, columnName: string, columnType: string | undefined) {
  if (!isBinaryColumn(columnName, columnType)) {
    return
  }

  event.stopPropagation()
  openBinaryPreview(rowKey, columnName)
}

function base64ToBytes(base64: string) {
  const raw = atob(base64)
  const bytes = new Uint8Array(raw.length)
  for (let index = 0; index < raw.length; index += 1) {
    bytes[index] = raw.charCodeAt(index)
  }
  return bytes
}

async function saveCellContent(rowKey: string, columnName: string) {
  closeContextMenu()
  const content = await ensureCellContent(rowKey, columnName)
  if (!content.base64Data) {
    return
  }

  const bytes = base64ToBytes(content.base64Data)
  const blob = new Blob([bytes], { type: content.mimeType || 'application/octet-stream' })
  const windowWithPicker = window as Window & {
    showSaveFilePicker?: (options?: unknown) => Promise<{
      createWritable: () => Promise<{ write: (data: Blob) => Promise<void>; close: () => Promise<void> }>
    }>
  }

  if (windowWithPicker.showSaveFilePicker) {
    const extension = content.suggestedFileName.includes('.') ? `.${content.suggestedFileName.split('.').pop()}` : '.bin'
    const handle = await windowWithPicker.showSaveFilePicker({
      suggestedName: content.suggestedFileName,
      types: [{
        description: content.mimeType,
        accept: {
          [content.mimeType || 'application/octet-stream']: [extension],
        },
      }],
    })
    const writable = await handle.createWritable()
    await writable.write(blob)
    await writable.close()
    return
  }

  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = content.suggestedFileName
  anchor.click()
  URL.revokeObjectURL(url)
}

async function handleEditorSave(payload: { valueKind: 'text' | 'binary' | 'null'; textValue?: string | null; base64Value?: string | null; setNull: boolean }) {
  const rowKey = editorState.value.rowKey
  const column = editorState.value.column
  if (!rowKey || !column) {
    return
  }

  editorState.value = {
    ...editorState.value,
    saving: true,
  }

  try {
    const previousRowKey = rowKey
    const columnName = column.name
    await store.updateTableCell({
      tableKey: props.tableKey,
      rowKey: previousRowKey,
      columnName,
      valueKind: payload.valueKind,
      textValue: payload.textValue ?? null,
      base64Value: payload.base64Value ?? null,
      setNull: payload.setNull,
    })

    const nextCache = { ...previewCache.value }
    delete nextCache[previewCacheKey(previousRowKey, columnName)]
    previewCache.value = nextCache
    editorState.value = {
      show: false,
      rowKey: null,
      column: null,
      foreignKey: null,
      value: undefined,
      saving: false,
    }
  }
  catch {
    editorState.value = {
      ...editorState.value,
      saving: false,
    }
  }
}

function handleWindowClick() {
  closeContextMenu()
}

onMounted(() => {
  window.addEventListener('click', handleWindowClick)
})

onBeforeUnmount(() => {
  window.removeEventListener('click', handleWindowClick)
})
</script>

<template>
  <n-card embedded class="workspace-panel grid-panel">
    <template #header>
      <div class="panel-header grid-panel-header-compact">
        <div class="grid-panel-title-row">
          <span class="grid-panel-kicker">主表数据</span>
          <h3>{{ tableMeta?.schema ? `${tableMeta.schema}.${tableMeta.name}` : tableMeta?.name }}</h3>
        </div>
        <div class="grid-panel-header-meta">
          <div class="panel-meta">{{ loadedRowCount }} / {{ totalRowCount }} rows</div>
        </div>
      </div>
    </template>

    <div class="grid-panel-body">
      <n-alert v-if="store.getTableError(props.tableKey)" type="warning" :show-icon="false" class="panel-inline-alert">
        {{ store.getTableError(props.tableKey) }}
      </n-alert>
      <n-alert v-else-if="store.getTableSearchError(props.tableKey)" type="warning" :show-icon="false" class="panel-inline-alert">
        {{ store.getTableSearchError(props.tableKey) }}
      </n-alert>

      <n-spin :show="store.isTableLoading(props.tableKey) || store.isSearchLoading(props.tableKey)" class="grid-panel-spin">
        <div v-if="table" class="grid-table-wrap">
          <template v-if="hasRows">
            <table class="grid-table">
              <thead>
                <tr>
                  <th
                    v-for="column in visibleColumns"
                    :key="column.name"
                    :style="columnStyle(column.name)"
                    :class="{ 'grid-header-sortable': store.isSortableColumn(column.name, column.type) }"
                    @click="handleHeaderSort(column.name, column.type)"
                  >
                    <n-tooltip trigger="hover">
                      <template #trigger>
                        <span class="grid-header-text">
                          <span>{{ column.name }}</span>
                          <span v-if="sortIndicator(column.name)" class="grid-sort-indicator">{{ sortIndicator(column.name) }}</span>
                        </span>
                      </template>
                      {{ displayColumnType(column) }}
                    </n-tooltip>
                    <button
                      type="button"
                      class="grid-resize-handle"
                      :title="`拖拽调整 ${column.name} 列宽，双击恢复自动宽度`"
                      @click.stop
                      @mousedown="beginResize($event, column.name)"
                      @dblclick.stop="resetColumnWidth(column.name)"
                    />
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="row in rows"
                  :key="row.rowKey"
                  class="grid-row"
                >
                  <td
                    v-for="(column, columnIndex) in visibleColumns"
                    :key="column.name"
                    :style="columnStyle(column.name)"
                    :class="{ 'grid-binary-value-cell': isBinaryColumn(column.name, column.type) }"
                    @mousedown="handleCellMouseDown($event, !!column.fk || isBinaryColumn(column.name, column.type) || isRowOpenCell(column.name, column.type, column.isPrimaryKey, columnIndex))"
                    @click="handleBinaryCellClick($event, row.rowKey, column.name, column.type)"
                    @dblclick="handleCellDoubleClick($event, row.rowKey, column, columnIndex, row[column.name] as CellValue)"
                    @contextmenu.prevent.stop="openCellContextMenu($event, row.rowKey, column, row[column.name] as CellValue)"
                  >
                    <button
                      v-if="column.fk"
                      type="button"
                      class="grid-link-button"
                      :title="cellValue(row, column.name, column.type)"
                      @click="handleForeignKeyClick(row.rowKey, column.name)"
                    >
                      {{ cellValue(row, column.name, column.type) }}
                    </button>
                    <span
                      v-else-if="column.isPrimaryKey"
                      class="grid-primary-value"
                      :title="cellValue(row, column.name, column.type)"
                      @dblclick="handlePrimaryCellDoubleClick($event, row.rowKey)"
                    >
                      {{ cellValue(row, column.name, column.type) }}
                    </span>
                    <span
                      v-else-if="isRowOpenCell(column.name, column.type, column.isPrimaryKey, columnIndex)"
                      class="grid-cell-text grid-detail-open-value"
                      :title="cellValue(row, column.name, column.type)"
                      @dblclick="handlePrimaryCellDoubleClick($event, row.rowKey)"
                    >
                      {{ cellValue(row, column.name, column.type) }}
                    </span>
                    <span
                      v-else
                      class="grid-cell-text"
                      :title="cellValue(row, column.name, column.type)"
                    >
                      {{ cellValue(row, column.name, column.type) }}
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>
          </template>
          <n-empty v-else description="当前筛选结果没有数据" />
        </div>
        <n-empty v-else description="表数据尚未加载完成" />
      </n-spin>

      <div v-if="table" class="grid-footer">
        <div class="grid-footer-meta">{{ searchActive ? '搜索结果' : '已加载' }} {{ loadedRowCount }} / {{ totalRowCount }} 行</div>
        <div class="grid-footer-actions">
          <n-button size="small" tertiary :disabled="!hasMoreRows || store.isTableLoading(props.tableKey) || store.isSearchLoading(props.tableKey)" @click="searchActive ? store.loadMoreSearchRows(props.tableKey) : store.loadMoreTableRows(props.tableKey)">
            再加载 {{ store.defaultPageSize }} 行
          </n-button>
          <n-button size="small" tertiary type="primary" :disabled="!hasMoreRows || store.isTableLoading(props.tableKey) || store.isSearchLoading(props.tableKey)" @click="searchActive ? store.loadAllSearchRows(props.tableKey) : store.loadAllTableRows(props.tableKey)">
            加载全部
          </n-button>
          <n-button v-if="searchActive" size="small" tertiary @click="store.clearActiveTableSearch()">
            清除搜索
          </n-button>
        </div>
      </div>
    </div>

    <div
      v-if="contextMenu?.show"
      class="grid-context-menu"
      :style="{ left: `${contextMenu.x}px`, top: `${contextMenu.y}px` }"
    >
      <button
        v-if="isEditableColumn(contextMenu.column)"
        type="button"
        class="grid-context-menu-item"
        @click="openCellEditor(contextMenu.rowKey, contextMenu.column, contextMenu.value)"
      >
        编辑单元格...
      </button>
      <button
        v-if="isBinaryColumn(contextMenu.column.name, contextMenu.column.type)"
        type="button"
        class="grid-context-menu-item"
        @click="openBinaryPreview(contextMenu.rowKey, contextMenu.column.name); closeContextMenu()"
      >
        预览二进制
      </button>
      <button
        v-if="isBinaryColumn(contextMenu.column.name, contextMenu.column.type)"
        type="button"
        class="grid-context-menu-item"
        @click="saveCellContent(contextMenu.rowKey, contextMenu.column.name)"
      >
        保存二进制到文件...
      </button>
    </div>

    <GridCellEditorModal
      v-model:show="editorState.show"
      :table-label="tableMeta?.schema ? `${tableMeta.schema}.${tableMeta.name}` : (tableMeta?.name ?? props.tableKey)"
      :row-key="editorState.rowKey"
      :column="editorState.column"
      :foreign-key="editorState.foreignKey"
      :value="editorState.value"
      :saving="editorState.saving"
      @save="handleEditorSave"
    />

    <n-modal v-model:show="previewState.show" preset="card" style="width: min(960px, 92vw)" :title="previewState.title">
      <n-spin :show="previewState.loading">
        <div v-if="previewState.error" class="binary-preview-empty">{{ previewState.error }}</div>
        <template v-else-if="previewState.content">
          <img v-if="previewState.content.kind === 'image' && previewImageUrl" :src="previewImageUrl" class="binary-preview-image">
          <pre v-else-if="previewState.content.kind === 'text'" class="binary-preview-text">{{ previewState.content.textContent }}</pre>
          <div v-else class="binary-preview-empty">该二进制内容不是可直接预览的图片或文本，但可以保存到本地文件。</div>

          <div class="binary-preview-meta">
            <span>{{ previewState.content.kind }}</span>
            <span>{{ previewState.content.mimeType }}</span>
            <span>{{ previewState.content.sizeBytes }} B</span>
          </div>
          <div class="binary-preview-actions">
            <n-button type="primary" @click="saveCellContent(previewState.content.rowKey, previewState.content.columnName)">保存到文件...</n-button>
          </div>
        </template>
      </n-spin>
    </n-modal>
  </n-card>
</template>
