<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { ChevronDown, OverflowMenuHorizontal } from '@vicons/carbon';
import { NAlert, NButton, NCheckbox, NEmpty, NIcon, NInput, NModal, NSelect, NSpin, NTag } from 'naive-ui';
import { useExplorerStore } from '../stores/explorer';
import type { TableColumn, TableDesignSection, TableDesignWorkspaceTab, ProviderType } from '../types/explorer';

type TypeEditorMode = 'none' | 'length' | 'length-or-max' | 'precision' | 'precision-scale' | 'scale'

type TypeCatalogEntry = {
  label: string
  value: string
  base: string
  mode: TypeEditorMode
  defaultLength?: string
  defaultPrecision?: string
  defaultScale?: string
}

type EditableColumn = {
  draftKey: string
  originalName: string | null
  originalComment: string | null
  name: string
  typeBase: string
  typeInput: string
  length: string
  precision: string
  scale: string
  comment: string
  isNullable: boolean
  isPrimaryKey: boolean
  isAutoGenerated: boolean
  isComputed: boolean
  isNew: boolean
}

let editableColumnDraftCounter = 0;

function createEditableColumnDraftKey(seed?: string | null) {
  editableColumnDraftCounter += 1;
  return `${seed ?? 'column'}:${editableColumnDraftCounter}`;
}

const props = defineProps<{
  tab: TableDesignWorkspaceTab
}>();

const store = useExplorerStore();
const design = computed(() => store.getTableDesign(props.tab.tableKey));
const designStatus = computed(() => store.getTableDesignStatus(props.tab.tableKey));
const saving = ref(false);
const draftColumns = ref<EditableColumn[]>([]);
const typeMenuRowKey = ref<string | null>(null);
const typeMenuAnchor = ref<HTMLElement | null>(null);
const typeMenuPosition = ref<{ top: number; left: number; width: number; height: number } | null>(null);
const commentEditorVisible = ref(false);
const commentEditorTarget = ref<EditableColumn | null>(null);
const commentEditorDraft = ref('');
const commentEditorAnchor = ref<HTMLElement | null>(null);
const commentEditorTextarea = ref<HTMLTextAreaElement | null>(null);
const commentEditorPosition = ref<{ top: number; left: number; width: number } | null>(null);
const createIndexVisible = ref(false);
const createIndexLoading = ref(false);
const createIndexError = ref<string | null>(null);
const createIndexName = ref('');
const createIndexUnique = ref(false);
const createIndexColumns = ref<string[]>([]);
const designContextMenu = ref<{ kind: 'column' | 'index'; name: string; x: number; y: number } | null>(null);

const PROVIDER_TYPE_CATALOG: Record<ProviderType, TypeCatalogEntry[]> = {
  sqlserver: [
    { label: 'bigint', value: 'bigint', base: 'bigint', mode: 'none' },
    { label: 'binary(50)', value: 'binary(50)', base: 'binary', mode: 'length', defaultLength: '50' },
    { label: 'bit', value: 'bit', base: 'bit', mode: 'none' },
    { label: 'char(10)', value: 'char(10)', base: 'char', mode: 'length', defaultLength: '10' },
    { label: 'date', value: 'date', base: 'date', mode: 'none' },
    { label: 'datetime', value: 'datetime', base: 'datetime', mode: 'none' },
    { label: 'datetime2(7)', value: 'datetime2(7)', base: 'datetime2', mode: 'scale', defaultScale: '7' },
    { label: 'datetimeoffset(7)', value: 'datetimeoffset(7)', base: 'datetimeoffset', mode: 'scale', defaultScale: '7' },
    { label: 'decimal(18,2)', value: 'decimal(18,2)', base: 'decimal', mode: 'precision-scale', defaultPrecision: '18', defaultScale: '2' },
    { label: 'float(53)', value: 'float(53)', base: 'float', mode: 'precision', defaultPrecision: '53' },
    { label: 'image', value: 'image', base: 'image', mode: 'none' },
    { label: 'int', value: 'int', base: 'int', mode: 'none' },
    { label: 'money', value: 'money', base: 'money', mode: 'none' },
    { label: 'nchar(10)', value: 'nchar(10)', base: 'nchar', mode: 'length', defaultLength: '10' },
    { label: 'ntext', value: 'ntext', base: 'ntext', mode: 'none' },
    { label: 'numeric(18,2)', value: 'numeric(18,2)', base: 'numeric', mode: 'precision-scale', defaultPrecision: '18', defaultScale: '2' },
    { label: 'nvarchar(255)', value: 'nvarchar(255)', base: 'nvarchar', mode: 'length-or-max', defaultLength: '255' },
    { label: 'nvarchar(max)', value: 'nvarchar(max)', base: 'nvarchar', mode: 'length-or-max', defaultLength: 'max' },
    { label: 'real', value: 'real', base: 'real', mode: 'none' },
    { label: 'smalldatetime', value: 'smalldatetime', base: 'smalldatetime', mode: 'none' },
    { label: 'smallint', value: 'smallint', base: 'smallint', mode: 'none' },
    { label: 'smallmoney', value: 'smallmoney', base: 'smallmoney', mode: 'none' },
    { label: 'text', value: 'text', base: 'text', mode: 'none' },
    { label: 'time(7)', value: 'time(7)', base: 'time', mode: 'scale', defaultScale: '7' },
    { label: 'timestamp', value: 'timestamp', base: 'timestamp', mode: 'none' },
    { label: 'tinyint', value: 'tinyint', base: 'tinyint', mode: 'none' },
    { label: 'uniqueidentifier', value: 'uniqueidentifier', base: 'uniqueidentifier', mode: 'none' },
    { label: 'varbinary(255)', value: 'varbinary(255)', base: 'varbinary', mode: 'length-or-max', defaultLength: '255' },
    { label: 'varbinary(max)', value: 'varbinary(max)', base: 'varbinary', mode: 'length-or-max', defaultLength: 'max' },
    { label: 'varchar(255)', value: 'varchar(255)', base: 'varchar', mode: 'length-or-max', defaultLength: '255' },
    { label: 'varchar(max)', value: 'varchar(max)', base: 'varchar', mode: 'length-or-max', defaultLength: 'max' },
    { label: 'xml', value: 'xml', base: 'xml', mode: 'none' },
  ],
  mysql: [
    { label: 'bigint', value: 'bigint', base: 'bigint', mode: 'none' },
    { label: 'binary(50)', value: 'binary(50)', base: 'binary', mode: 'length', defaultLength: '50' },
    { label: 'bit(1)', value: 'bit(1)', base: 'bit', mode: 'length', defaultLength: '1' },
    { label: 'blob', value: 'blob', base: 'blob', mode: 'none' },
    { label: 'char(10)', value: 'char(10)', base: 'char', mode: 'length', defaultLength: '10' },
    { label: 'date', value: 'date', base: 'date', mode: 'none' },
    { label: 'datetime', value: 'datetime', base: 'datetime', mode: 'scale', defaultScale: '0' },
    { label: 'decimal(18,2)', value: 'decimal(18,2)', base: 'decimal', mode: 'precision-scale', defaultPrecision: '18', defaultScale: '2' },
    { label: 'double', value: 'double', base: 'double', mode: 'none' },
    { label: 'enum', value: 'enum', base: 'enum', mode: 'none' },
    { label: 'float', value: 'float', base: 'float', mode: 'none' },
    { label: 'int', value: 'int', base: 'int', mode: 'none' },
    { label: 'json', value: 'json', base: 'json', mode: 'none' },
    { label: 'longblob', value: 'longblob', base: 'longblob', mode: 'none' },
    { label: 'longtext', value: 'longtext', base: 'longtext', mode: 'none' },
    { label: 'mediumblob', value: 'mediumblob', base: 'mediumblob', mode: 'none' },
    { label: 'mediumint', value: 'mediumint', base: 'mediumint', mode: 'none' },
    { label: 'mediumtext', value: 'mediumtext', base: 'mediumtext', mode: 'none' },
    { label: 'numeric(18,2)', value: 'numeric(18,2)', base: 'numeric', mode: 'precision-scale', defaultPrecision: '18', defaultScale: '2' },
    { label: 'set', value: 'set', base: 'set', mode: 'none' },
    { label: 'smallint', value: 'smallint', base: 'smallint', mode: 'none' },
    { label: 'text', value: 'text', base: 'text', mode: 'none' },
    { label: 'time(0)', value: 'time(0)', base: 'time', mode: 'scale', defaultScale: '0' },
    { label: 'timestamp(0)', value: 'timestamp(0)', base: 'timestamp', mode: 'scale', defaultScale: '0' },
    { label: 'tinyblob', value: 'tinyblob', base: 'tinyblob', mode: 'none' },
    { label: 'tinyint', value: 'tinyint', base: 'tinyint', mode: 'none' },
    { label: 'tinytext', value: 'tinytext', base: 'tinytext', mode: 'none' },
    { label: 'varbinary(255)', value: 'varbinary(255)', base: 'varbinary', mode: 'length', defaultLength: '255' },
    { label: 'varchar(255)', value: 'varchar(255)', base: 'varchar', mode: 'length', defaultLength: '255' },
    { label: 'year', value: 'year', base: 'year', mode: 'none' },
  ],
  postgresql: [
    { label: 'bigint', value: 'bigint', base: 'bigint', mode: 'none' },
    { label: 'bigserial', value: 'bigserial', base: 'bigserial', mode: 'none' },
    { label: 'bit(1)', value: 'bit(1)', base: 'bit', mode: 'length', defaultLength: '1' },
    { label: 'boolean', value: 'boolean', base: 'boolean', mode: 'none' },
    { label: 'bytea', value: 'bytea', base: 'bytea', mode: 'none' },
    { label: 'char(10)', value: 'char(10)', base: 'char', mode: 'length', defaultLength: '10' },
    { label: 'date', value: 'date', base: 'date', mode: 'none' },
    { label: 'double precision', value: 'double precision', base: 'double precision', mode: 'none' },
    { label: 'integer', value: 'integer', base: 'integer', mode: 'none' },
    { label: 'json', value: 'json', base: 'json', mode: 'none' },
    { label: 'jsonb', value: 'jsonb', base: 'jsonb', mode: 'none' },
    { label: 'numeric(18,2)', value: 'numeric(18,2)', base: 'numeric', mode: 'precision-scale', defaultPrecision: '18', defaultScale: '2' },
    { label: 'real', value: 'real', base: 'real', mode: 'none' },
    { label: 'smallint', value: 'smallint', base: 'smallint', mode: 'none' },
    { label: 'smallserial', value: 'smallserial', base: 'smallserial', mode: 'none' },
    { label: 'serial', value: 'serial', base: 'serial', mode: 'none' },
    { label: 'text', value: 'text', base: 'text', mode: 'none' },
    { label: 'time(6)', value: 'time(6)', base: 'time', mode: 'scale', defaultScale: '6' },
    { label: 'timestamp(6)', value: 'timestamp(6)', base: 'timestamp', mode: 'scale', defaultScale: '6' },
    { label: 'timestamptz(6)', value: 'timestamptz(6)', base: 'timestamptz', mode: 'scale', defaultScale: '6' },
    { label: 'uuid', value: 'uuid', base: 'uuid', mode: 'none' },
    { label: 'varchar(255)', value: 'varchar(255)', base: 'varchar', mode: 'length', defaultLength: '255' },
    { label: 'xml', value: 'xml', base: 'xml', mode: 'none' },
  ],
  sqlite: [
    { label: 'INTEGER', value: 'INTEGER', base: 'INTEGER', mode: 'none' },
    { label: 'TEXT', value: 'TEXT', base: 'TEXT', mode: 'none' },
    { label: 'REAL', value: 'REAL', base: 'REAL', mode: 'none' },
    { label: 'NUMERIC', value: 'NUMERIC', base: 'NUMERIC', mode: 'none' },
    { label: 'BLOB', value: 'BLOB', base: 'BLOB', mode: 'none' },
    { label: 'VARCHAR(255)', value: 'VARCHAR(255)', base: 'VARCHAR', mode: 'length', defaultLength: '255' },
    { label: 'NVARCHAR(255)', value: 'NVARCHAR(255)', base: 'NVARCHAR', mode: 'length', defaultLength: '255' },
    { label: 'DECIMAL(18,2)', value: 'DECIMAL(18,2)', base: 'DECIMAL', mode: 'precision-scale', defaultPrecision: '18', defaultScale: '2' },
    { label: 'BOOLEAN', value: 'BOOLEAN', base: 'BOOLEAN', mode: 'none' },
    { label: 'DATE', value: 'DATE', base: 'DATE', mode: 'none' },
    { label: 'DATETIME', value: 'DATETIME', base: 'DATETIME', mode: 'none' },
    { label: 'JSON', value: 'JSON', base: 'JSON', mode: 'none' },
  ],
};

function normalizeTypeKey(value: string) {
  return value.replace(/\s+/g, ' ').trim().toLowerCase();
}

function providerCatalog(provider: ProviderType) {
  return PROVIDER_TYPE_CATALOG[provider] ?? [];
}

function findTypeEntry(provider: ProviderType, rawType: string) {
  const normalized = normalizeTypeKey(rawType);
  return providerCatalog(provider).find((entry) => normalizeTypeKey(entry.value) === normalized || normalizeTypeKey(entry.base) === normalized) ?? null;
}

function inferEditorMode(provider: ProviderType, baseType: string, length: string, precision: string, scale: string): TypeEditorMode {
  const entry = findTypeEntry(provider, baseType);
  if (entry) {
    return entry.mode;
  }

  if (precision && scale) {
    return 'precision-scale';
  }

  if (precision) {
    return 'precision';
  }

  if (scale) {
    return 'scale';
  }

  if (length.toLowerCase() === 'max') {
    return 'length-or-max';
  }

  if (length) {
    return 'length';
  }

  return 'none';
}

function buildTypeInput(baseType: string, mode: TypeEditorMode, length: string, precision: string, scale: string) {
  const base = baseType.trim();
  if (!base) {
    return '';
  }

  if (mode === 'precision-scale' && precision.trim()) {
    return `${base}(${precision.trim()}${scale.trim() ? `,${scale.trim()}` : ''})`;
  }

  if (mode === 'precision' && precision.trim()) {
    return `${base}(${precision.trim()})`;
  }

  if (mode === 'scale' && scale.trim()) {
    return `${base}(${scale.trim()})`;
  }

  if ((mode === 'length' || mode === 'length-or-max') && length.trim()) {
    return `${base}(${length.trim()})`;
  }

  return base;
}

function parseTypeInput(provider: ProviderType, rawInput: string, fallback?: Partial<EditableColumn>) {
  const trimmed = rawInput.trim();
  const match = /^([^()]+?)(?:\(([^)]*)\))?$/.exec(trimmed);
  const baseType = match?.[1]?.trim() || trimmed || fallback?.typeBase || '';
  const args = (match?.[2] ?? '').split(',').map((item) => item.trim()).filter(Boolean);
  const entry = findTypeEntry(provider, trimmed || baseType);

  let length = fallback?.length ?? '';
  let precision = fallback?.precision ?? '';
  let scale = fallback?.scale ?? '';

  if (args.length === 1) {
    const firstArg = args[0] ?? '';
    if (entry?.mode === 'precision') {
      precision = firstArg;
      scale = '';
      length = '';
    }
    else if (entry?.mode === 'scale') {
      scale = firstArg;
      precision = '';
      length = '';
    }
    else {
      length = firstArg;
      precision = '';
      scale = '';
    }
  }
  else if (args.length >= 2) {
    precision = args[0] ?? '';
    scale = args[1] ?? '';
    length = '';
  }
  else if (entry?.defaultLength !== undefined && !length && (entry.mode === 'length' || entry.mode === 'length-or-max')) {
    length = entry.defaultLength;
  }
  else if (entry?.defaultPrecision !== undefined && !precision && (entry.mode === 'precision' || entry.mode === 'precision-scale')) {
    precision = entry.defaultPrecision;
    scale = entry.defaultScale ?? scale;
  }
  else if (entry?.defaultScale !== undefined && !scale && entry.mode === 'scale') {
    scale = entry.defaultScale;
  }

  const mode = entry?.mode ?? inferEditorMode(provider, baseType, length, precision, scale);
  return {
    typeBase: baseType,
    typeInput: buildTypeInput(baseType, mode, length, precision, scale) || trimmed,
    length,
    precision,
    scale,
  };
}

function buildEditableColumns(columns: TableColumn[]) {
  const provider = design.value?.provider ?? 'sqlserver';
  return columns.map((column) => {
    const length = column.maxLength === null || column.maxLength === undefined
      ? ''
      : column.maxLength < 0
        ? 'max'
        : String(column.maxLength);
    const precision = column.numericPrecision === null || column.numericPrecision === undefined ? '' : String(column.numericPrecision);
    const scale = column.numericScale === null || column.numericScale === undefined ? '' : String(column.numericScale);
    const parsed = parseTypeInput(provider, buildTypeInput(column.type, inferEditorMode(provider, column.type, length, precision, scale), length, precision, scale), {
      typeBase: column.type,
      length,
      precision,
      scale,
    });

    return {
      draftKey: createEditableColumnDraftKey(column.name),
      originalName: column.name,
      originalComment: column.comment ?? null,
      name: column.name,
      typeBase: parsed.typeBase,
      typeInput: parsed.typeBase,
      length: parsed.length,
      precision: parsed.precision,
      scale: parsed.scale,
      comment: column.comment ?? '',
      isNullable: column.isNullable !== false,
      isPrimaryKey: !!column.isPrimaryKey,
      isAutoGenerated: !!column.isAutoGenerated,
      isComputed: !!column.isComputed,
      isNew: false,
    };
  });
}

/** 已删除的原始列名（仅限非 isNew 的既有列） */
const droppedColumns = ref<string[]>([]);

watch(design, (value) => {
  draftColumns.value = buildEditableColumns(value?.columns ?? []);
  droppedColumns.value = [];
}, { immediate: true });

const selectedSection = computed(() => props.tab.selectedSection);
const selectedEntry = computed(() => props.tab.selectedEntry ?? null);
const isReadOnlyObject = computed(() => design.value?.objectType === 'view');
const objectLabel = computed(() => design.value?.objectType === 'view' ? '视图' : '表');

const dirty = computed(() => {
  if (isReadOnlyObject.value) {
    return false;
  }

  if (droppedColumns.value.length > 0) {
    return true;
  }

  const original = buildEditableColumns(design.value?.columns ?? []);
  if (original.length !== draftColumns.value.length) {
    return true;
  }

  return draftColumns.value.some((column, index) => {
    const source = original[index];
    return !source
      || source.name !== column.name
      || source.typeBase !== column.typeBase
      || source.length !== column.length
      || source.precision !== column.precision
      || source.scale !== column.scale
      || source.comment !== column.comment
      || source.isNullable !== column.isNullable
      || source.isNew !== column.isNew;
  });
});

const providerTypeOptions = computed(() => (design.value ? providerCatalog(design.value.provider) : []).map((entry) => ({ label: entry.label, value: entry.value })));
const supportsColumnComment = computed(() => design.value?.provider !== 'sqlite');
const indexColumnOptions = computed(() => (design.value?.columns ?? []).map((column) => ({ label: column.name, value: column.name })));
const sectionTabs = computed(() => {
  if (!design.value) {
    return [];
  }

  const tabs: Array<{ key: TableDesignSection; label: string; count: number }> = [
    { key: 'columns' as TableDesignSection, label: '字段', count: draftColumns.value.length },
    { key: 'indexes' as TableDesignSection, label: '索引', count: design.value.indexes.length },
    { key: 'triggers' as TableDesignSection, label: '触发器', count: design.value.triggers.length },
    { key: 'statistics' as TableDesignSection, label: '统计信息', count: design.value.statistics.length },
  ];

  if (design.value.objectType === 'table') {
    tabs.splice(2, 0, { key: 'foreignKeys' as TableDesignSection, label: '外键', count: design.value.foreignKeys.length });
  }

  return tabs;
});

function tableLabel() {
  const current = design.value;
  if (!current) {
    return props.tab.tableKey;
  }

  return current.schema ? `${current.schema}.${current.name}` : current.name;
}

function canEditColumn(column: EditableColumn) {
  if (isReadOnlyObject.value) {
    return false;
  }

  return column.isNew || (!column.isPrimaryKey && !column.isAutoGenerated && !column.isComputed);
}

function focusSection(section: TableDesignSection, entry: string | null = null) {
  store.updateDesignTabSelection(props.tab.id, section, entry);
}

function addColumn() {
  if (isReadOnlyObject.value) {
    return;
  }

  draftColumns.value = [
    ...draftColumns.value,
    {
      draftKey: createEditableColumnDraftKey('new-column'),
      originalName: null,
      originalComment: null,
      name: `NewColumn${draftColumns.value.length + 1}`,
      typeBase: design.value?.provider === 'postgresql' ? 'varchar' : design.value?.provider === 'mysql' ? 'varchar' : design.value?.provider === 'sqlite' ? 'TEXT' : 'nvarchar',
      typeInput: design.value?.provider === 'sqlite' ? 'TEXT' : 'nvarchar',
      length: design.value?.provider === 'sqlite' ? '' : '255',
      precision: '',
      scale: '',
      comment: '',
      isNullable: true,
      isPrimaryKey: false,
      isAutoGenerated: false,
      isComputed: false,
      isNew: true,
    },
  ];
  focusSection('columns', draftColumns.value[draftColumns.value.length - 1]?.name ?? null);
}

function columnTypeDeclaration(column: EditableColumn) {
  return buildTypeInput(column.typeBase, typeEditorMode(column), column.length, column.precision, column.scale).trim();
}

function typeEditorMode(column: EditableColumn) {
  return inferEditorMode(design.value?.provider ?? 'sqlserver', column.typeBase, column.length, column.precision, column.scale);
}

function applyTypeInput(column: EditableColumn, nextValue: string) {
  const parsed = parseTypeInput(design.value?.provider ?? 'sqlserver', nextValue, column);
  column.typeBase = parsed.typeBase;
  column.typeInput = parsed.typeBase;
  column.length = parsed.length;
  column.precision = parsed.precision;
  column.scale = parsed.scale;
}

function syncTypeInput(column: EditableColumn) {
  column.typeInput = column.typeBase;
}

function selectTypeSuggestion(column: EditableColumn, nextValue: string) {
  applyTypeInput(column, nextValue);
}

function columnRowKey(column: EditableColumn) {
  return column.originalName ?? column.draftKey;
}

function updateColumnName(column: EditableColumn, nextValue: string) {
  const previousSelectionKey = column.originalName ?? column.name;
  column.name = nextValue;

  if (selectedSection.value === 'columns' && selectedEntry.value === previousSelectionKey) {
    focusSection('columns', column.originalName ?? nextValue);
  }
}

function primaryParameterValue(column: EditableColumn) {
  const mode = typeEditorMode(column);
  if (mode === 'length' || mode === 'length-or-max') {
    return column.length;
  }

  if (mode === 'precision-scale') {
    return column.precision;
  }

  if (mode === 'precision') {
    return column.precision;
  }

  if (mode === 'scale') {
    return column.scale;
  }

  return '';
}

function secondaryParameterValue(column: EditableColumn) {
  return typeEditorMode(column) === 'precision-scale' ? column.scale : '';
}

function showsPrimaryParameter(column: EditableColumn) {
  return typeEditorMode(column) !== 'none';
}

function showsSecondaryParameter(column: EditableColumn) {
  return typeEditorMode(column) === 'precision-scale';
}

function setPrimaryParameterValue(column: EditableColumn, nextValue: string) {
  const value = nextValue.trim();
  const mode = typeEditorMode(column);
  if (mode === 'length' || mode === 'length-or-max') {
    column.length = value;
  }
  else if (mode === 'precision-scale') {
    column.precision = value;
  }
  else if (mode === 'precision') {
    column.precision = value;
  }
  else if (mode === 'scale') {
    column.scale = value;
  }

  syncTypeInput(column);
}

function setSecondaryParameterValue(column: EditableColumn, nextValue: string) {
  column.scale = nextValue.trim();
  syncTypeInput(column);
}

function selectTypeFromMenu(column: EditableColumn, value: string) {
  selectTypeSuggestion(column, value);
  typeMenuRowKey.value = null;
  typeMenuAnchor.value = null;
  typeMenuPosition.value = null;
}

function updateTypeMenuPosition() {
  const anchor = typeMenuAnchor.value;
  if (!anchor) {
    typeMenuPosition.value = null;
    return;
  }

  const rect = anchor.getBoundingClientRect();
  const width = Math.min(Math.max(Math.round(rect.width), 170), window.innerWidth - 20);
  const height = Math.min(196, Math.max(116, window.innerHeight - 120));
  let left = rect.left;
  if (left + width > window.innerWidth - 10) {
    left = window.innerWidth - width - 10;
  }
  left = Math.max(10, left);

  let top = rect.bottom + 4;
  if (top + height > window.innerHeight - 10) {
    top = Math.max(10, rect.top - height - 4);
  }

  typeMenuPosition.value = {
    top,
    left,
    width,
    height,
  };
}

function toggleTypeMenu(column: EditableColumn, event: MouseEvent) {
  if (!canEditColumn(column)) {
    return;
  }

  const key = columnRowKey(column);
  if (typeMenuRowKey.value === key) {
    typeMenuRowKey.value = null;
    typeMenuAnchor.value = null;
    typeMenuPosition.value = null;
    return;
  }

  commentEditorVisible.value = false;
  commentEditorTarget.value = null;
  commentEditorDraft.value = '';
  commentEditorAnchor.value = null;
  commentEditorPosition.value = null;
  typeMenuAnchor.value = (event.currentTarget as HTMLElement | null)?.closest('.table-design-type-editor') as HTMLElement | null;
  updateTypeMenuPosition();
  typeMenuRowKey.value = key;
}

function activeTypeMenuColumn() {
  const key = typeMenuRowKey.value;
  return key ? draftColumns.value.find((column) => columnRowKey(column) === key) ?? null : null;
}

function isActiveTypeOption(optionValue: string) {
  const column = activeTypeMenuColumn();
  if (!column) {
    return false;
  }

  return normalizeTypeKey(columnTypeDeclaration(column) || column.typeBase) === normalizeTypeKey(optionValue)
    || normalizeTypeKey(column.typeBase) === normalizeTypeKey(optionValue);
}

function updateCommentEditorPosition() {
  const anchor = commentEditorAnchor.value;
  if (!anchor) {
    commentEditorPosition.value = null;
    return;
  }

  const rect = anchor.getBoundingClientRect();
  const width = Math.min(Math.max(rect.width + 28, 280), Math.max(280, window.innerWidth - 24));
  let left = Math.min(rect.left, window.innerWidth - width - 12);
  left = Math.max(12, left);

  const estimatedHeight = 196;
  let top = rect.bottom + 6;
  if (top + estimatedHeight > window.innerHeight - 12) {
    top = Math.max(12, rect.top - estimatedHeight - 6);
  }

  commentEditorPosition.value = {
    top,
    left,
    width,
  };
}

function openCommentEditor(column: EditableColumn, event: MouseEvent) {
  if (!canEditColumn(column)) {
    return;
  }

  typeMenuRowKey.value = null;
  commentEditorTarget.value = column;
  commentEditorDraft.value = column.comment;
  commentEditorAnchor.value = (event.currentTarget as HTMLElement | null)?.closest('.table-design-comment-editor') as HTMLElement | null;
  updateCommentEditorPosition();
  commentEditorVisible.value = true;
}

function focusCommentEditorSoon() {
  requestAnimationFrame(() => {
    requestAnimationFrame(() => {
      const textarea = commentEditorTextarea.value;
      if (textarea) {
        textarea.focus();
        textarea.setSelectionRange(textarea.value.length, textarea.value.length);
      }
    });
  });
}

function closeCommentEditor() {
  commentEditorVisible.value = false;
  commentEditorTarget.value = null;
  commentEditorDraft.value = '';
  commentEditorAnchor.value = null;
  commentEditorPosition.value = null;
}

function applyCommentEditor() {
  if (commentEditorTarget.value) {
    commentEditorTarget.value.comment = commentEditorDraft.value;
  }

  closeCommentEditor();
}

watch(commentEditorVisible, async (visible) => {
  if (!visible) {
    return;
  }

  await nextTick();
  updateCommentEditorPosition();
  focusCommentEditorSoon();
}, { flush: 'post' });

watch(commentEditorVisible, (visible, _, onCleanup) => {
  if (!visible) {
    return;
  }

  const handlePointerDown = (event: MouseEvent) => {
    const target = event.target as Node | null;
    if (!target) {
      closeCommentEditor();
      return;
    }

    if (commentEditorTextarea.value?.closest('.table-design-comment-overlay')?.contains(target)) {
      return;
    }

    if (commentEditorAnchor.value?.contains(target)) {
      return;
    }

    closeCommentEditor();
  };

  const handleViewportChange = () => {
    updateCommentEditorPosition();
  };

  const handleEscape = (event: KeyboardEvent) => {
    if (event.key === 'Escape') {
      event.preventDefault();
      closeCommentEditor();
    }
  };

  window.addEventListener('mousedown', handlePointerDown, true);
  window.addEventListener('resize', handleViewportChange);
  window.addEventListener('scroll', handleViewportChange, true);
  window.addEventListener('keydown', handleEscape, true);

  onCleanup(() => {
    window.removeEventListener('mousedown', handlePointerDown, true);
    window.removeEventListener('resize', handleViewportChange);
    window.removeEventListener('scroll', handleViewportChange, true);
    window.removeEventListener('keydown', handleEscape, true);
  });
});

watch(typeMenuRowKey, (rowKey, _, onCleanup) => {
  if (!rowKey) {
    return;
  }

  const handlePointerDown = (event: MouseEvent) => {
    const target = event.target as Node | null;
    if (!target) {
      typeMenuRowKey.value = null;
      typeMenuAnchor.value = null;
      typeMenuPosition.value = null;
      return;
    }

    if ((target as HTMLElement).closest('.table-design-type-overlay')) {
      return;
    }

    if (typeMenuAnchor.value?.contains(target)) {
      return;
    }

    typeMenuRowKey.value = null;
    typeMenuAnchor.value = null;
    typeMenuPosition.value = null;
  };

  const handleViewportChange = () => {
    updateTypeMenuPosition();
  };

  const handleEscape = (event: KeyboardEvent) => {
    if (event.key === 'Escape') {
      event.preventDefault();
      typeMenuRowKey.value = null;
      typeMenuAnchor.value = null;
      typeMenuPosition.value = null;
    }
  };

  window.addEventListener('mousedown', handlePointerDown, true);
  window.addEventListener('resize', handleViewportChange);
  window.addEventListener('scroll', handleViewportChange, true);
  window.addEventListener('keydown', handleEscape, true);

  onCleanup(() => {
    window.removeEventListener('mousedown', handlePointerDown, true);
    window.removeEventListener('resize', handleViewportChange);
    window.removeEventListener('scroll', handleViewportChange, true);
    window.removeEventListener('keydown', handleEscape, true);
  });
});

function quoteIdentifier(provider: ProviderType, value: string) {
  if (provider === 'mysql') {
    return `\`${value.replace(/`/g, '``')}\``;
  }

  if (provider === 'postgresql' || provider === 'sqlite') {
    return `"${value.replace(/"/g, '""')}"`;
  }

  return `[${value.replace(/\]/g, ']]')}]`;
}

function quoteIndexName(provider: ProviderType, value: string) {
  return quoteIdentifier(provider, value);
}

function qualifiedTable(provider: ProviderType, schema: string | null | undefined, tableName: string) {
  return schema
    ? `${quoteIdentifier(provider, schema)}.${quoteIdentifier(provider, tableName)}`
    : quoteIdentifier(provider, tableName);
}

function buildCreateIndexSql() {
  const current = design.value;
  if (!current) {
    throw new Error('表设计尚未加载完成。');
  }

  const indexName = createIndexName.value.trim();
  if (!indexName) {
    throw new Error('索引名称不能为空。');
  }

  if (!createIndexColumns.value.length) {
    throw new Error('请至少选择一个索引列。');
  }

  if (current.indexes.some((item) => item.name.toLowerCase() === indexName.toLowerCase())) {
    throw new Error(`索引 ${indexName} 已存在。`);
  }

  const qualifiedColumns = createIndexColumns.value.map((column) => quoteIdentifier(current.provider, column)).join(', ');
  const uniqueKeyword = createIndexUnique.value ? 'UNIQUE ' : '';
  const tableName = qualifiedTable(current.provider, current.schema, current.name);

  return `CREATE ${uniqueKeyword}INDEX ${quoteIndexName(current.provider, indexName)} ON ${tableName} (${qualifiedColumns})`;
}

function openCreateIndexDialog() {
  createIndexVisible.value = true;
  createIndexLoading.value = false;
  createIndexError.value = null;
  createIndexUnique.value = false;
  createIndexColumns.value = [];
  createIndexName.value = '';
}

function closeCreateIndexDialog() {
  createIndexVisible.value = false;
  createIndexLoading.value = false;
  createIndexError.value = null;
}

async function submitCreateIndex() {
  let sql = '';
  try {
    sql = buildCreateIndexSql();
  }
  catch (error) {
    createIndexError.value = error instanceof Error ? error.message : '索引定义无效';
    return;
  }

  createIndexLoading.value = true;
  createIndexError.value = null;
  try {
    await store.executeTableDesignSql(props.tab.tableKey, sql, '索引已创建');
    closeCreateIndexDialog();
    focusSection('indexes', createIndexName.value.trim());
  }
  catch (error) {
    createIndexError.value = error instanceof Error ? error.message : '索引创建失败';
  }
  finally {
    createIndexLoading.value = false;
  }
}

function openDesignContextMenu(event: MouseEvent, kind: 'column' | 'index', name: string) {
  event.preventDefault();
  focusSection(kind === 'column' ? 'columns' : 'indexes', name);
  designContextMenu.value = {
    kind,
    name,
    x: Math.max(8, Math.min(event.clientX, window.innerWidth - 168)),
    y: Math.max(8, Math.min(event.clientY, window.innerHeight - 72)),
  };
}

function closeDesignContextMenu() {
  designContextMenu.value = null;
}

async function handleContextDelete() {
  const target = designContextMenu.value;
  if (!target) {
    return;
  }

  closeDesignContextMenu();
  try {
    if (target.kind === 'column') {
      await store.deleteDesignColumn(props.tab.tableKey, target.name);
      focusSection('columns');
      return;
    }

    await store.deleteDesignIndex(props.tab.tableKey, target.name);
    focusSection('indexes');
  }
  catch (error) {
    store.showNotice('warning', error instanceof Error ? error.message : target.kind === 'column' ? '字段删除失败' : '索引删除失败');
  }
}

function normalizeComment(comment: string | null | undefined) {
  return (comment ?? '').trim();
}

function sqlLiteral(value: string) {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlUnicodeLiteral(value: string) {
  return `N'${value.replace(/'/g, "''")}'`;
}

function buildCommentStatements(provider: ProviderType, schema: string | null | undefined, tableName: string, columnName: string, previousComment: string | null | undefined, nextComment: string | null | undefined) {
  const before = normalizeComment(previousComment);
  const after = normalizeComment(nextComment);
  if (before === after) {
    return [];
  }

  if (provider === 'sqlite') {
    if (after || before) {
      throw new Error('SQLite 当前不支持列注释。');
    }

    return [];
  }

  if (provider === 'postgresql') {
    const qualifiedColumn = `${qualifiedTable(provider, schema, tableName)}.${quoteIdentifier(provider, columnName)}`;
    return [`COMMENT ON COLUMN ${qualifiedColumn} IS ${after ? sqlLiteral(after) : 'NULL'}`];
  }

  if (provider === 'sqlserver') {
    const schemaName = schema ?? 'dbo';
    if (before && !after) {
      return [`EXEC sp_dropextendedproperty @name = N'MS_Description', @level0type = N'SCHEMA', @level0name = ${sqlUnicodeLiteral(schemaName)}, @level1type = N'TABLE', @level1name = ${sqlUnicodeLiteral(tableName)}, @level2type = N'COLUMN', @level2name = ${sqlUnicodeLiteral(columnName)}`];
    }

    const qualifiedObjectName = `[${schemaName.replace(/]/g, ']]')}].[${tableName.replace(/]/g, ']]')}]`;
    return [
      `DECLARE @table_object_id int = OBJECT_ID(${sqlUnicodeLiteral(qualifiedObjectName)});\nDECLARE @column_id int = COLUMNPROPERTY(@table_object_id, ${sqlUnicodeLiteral(columnName)}, 'ColumnId');\nIF EXISTS (SELECT 1 FROM sys.extended_properties WHERE class = 1 AND major_id = @table_object_id AND minor_id = @column_id AND name = N'MS_Description')\n    EXEC sp_updateextendedproperty @name = N'MS_Description', @value = ${sqlUnicodeLiteral(after)}, @level0type = N'SCHEMA', @level0name = ${sqlUnicodeLiteral(schemaName)}, @level1type = N'TABLE', @level1name = ${sqlUnicodeLiteral(tableName)}, @level2type = N'COLUMN', @level2name = ${sqlUnicodeLiteral(columnName)}\nELSE\n    EXEC sp_addextendedproperty @name = N'MS_Description', @value = ${sqlUnicodeLiteral(after)}, @level0type = N'SCHEMA', @level0name = ${sqlUnicodeLiteral(schemaName)}, @level1type = N'TABLE', @level1name = ${sqlUnicodeLiteral(tableName)}, @level2type = N'COLUMN', @level2name = ${sqlUnicodeLiteral(columnName)}`,
    ];
  }

  return [];
}

function buildAlterSql() {
  const current = design.value;
  if (!current) {
    throw new Error('表设计尚未加载完成。');
  }

  const tableName = qualifiedTable(current.provider, current.schema, current.name);
  const statements: string[] = [];

  for (const column of draftColumns.value) {
    applyTypeInput(column, column.typeInput);
    const name = column.name.trim();
    const typeDecl = columnTypeDeclaration(column);
    if (!name) {
      throw new Error('字段名不能为空。');
    }

    if (!typeDecl) {
      throw new Error(`字段 ${name} 的类型不能为空。`);
    }

    /* 类型名/参数直接拼入 SQL（不是标识符也不是字符串字面量），必须严格校验防止注入。
       类型名仅允许字母、数字、空格、下划线；参数仅允许数字或 'max'。 */
    if (!/^[A-Za-z_][A-Za-z0-9_ ]*$/.test(column.typeBase.trim())) {
      throw new Error(`字段 ${name} 的类型名 "${column.typeBase}" 包含非法字符。`);
    }

    const dimensionPattern = /^(?:\d+|max)?$/i;
    if (!dimensionPattern.test(column.length.trim())) {
      throw new Error(`字段 ${name} 的大小参数 "${column.length}" 包含非法字符，仅允许数字或 max。`);
    }

    if (!dimensionPattern.test(column.precision.trim())) {
      throw new Error(`字段 ${name} 的精度参数 "${column.precision}" 包含非法字符，仅允许数字。`);
    }

    if (!dimensionPattern.test(column.scale.trim())) {
      throw new Error(`字段 ${name} 的比例参数 "${column.scale}" 包含非法字符，仅允许数字。`);
    }
  }

  const duplicate = draftColumns.value
    .map((column) => column.name.trim().toLowerCase())
    .find((name, index, list) => list.indexOf(name) !== index);
  if (duplicate) {
    throw new Error(`存在重复字段名：${duplicate}`);
  }

  for (const draft of draftColumns.value) {
    const nextName = draft.name.trim();
    const nextType = columnTypeDeclaration(draft);
    const nextNullable = draft.isPrimaryKey ? false : draft.isNullable;

    if (draft.isNew) {
      if (current.provider === 'sqlite' && !draft.isNullable) {
        throw new Error('SQLite 新增字段当前只支持可空列。');
      }

      const commentSql = normalizeComment(draft.comment);
      const addStatement = current.provider === 'mysql'
        ? `ALTER TABLE ${tableName} ADD ${quoteIdentifier(current.provider, nextName)} ${nextType}${nextNullable ? ' NULL' : ' NOT NULL'}${commentSql ? ` COMMENT ${sqlLiteral(commentSql)}` : ''}`
        : `ALTER TABLE ${tableName} ADD ${quoteIdentifier(current.provider, nextName)} ${nextType}${nextNullable ? ' NULL' : ' NOT NULL'}`;
      statements.push(addStatement);
      statements.push(...buildCommentStatements(current.provider, current.schema, current.name, nextName, null, draft.comment));
      continue;
    }

    const original = current.columns.find((column) => column.name === draft.originalName);
    if (!original) {
      continue;
    }

    const nameChanged = original.name !== nextName;
    const typeChanged = original.type !== draft.typeBase
      || ((original.maxLength === null || original.maxLength === undefined ? '' : original.maxLength < 0 ? 'max' : String(original.maxLength)) !== draft.length)
      || ((original.numericPrecision === null || original.numericPrecision === undefined ? '' : String(original.numericPrecision)) !== draft.precision)
      || ((original.numericScale === null || original.numericScale === undefined ? '' : String(original.numericScale)) !== draft.scale);
    const nullableChanged = (original.isNullable !== false) !== draft.isNullable;
    const commentChanged = normalizeComment(original.comment) !== normalizeComment(draft.comment);
    if (!nameChanged && !typeChanged && !nullableChanged && !commentChanged) {
      continue;
    }

    if ((original.isPrimaryKey || original.isAutoGenerated || original.isComputed) && (nameChanged || typeChanged || nullableChanged)) {
      throw new Error(`字段 ${original.name} 当前不支持在设计页修改。`);
    }

    if (current.provider === 'mysql') {
      const commentSql = normalizeComment(draft.comment);
      statements.push(`ALTER TABLE ${tableName} CHANGE COLUMN ${quoteIdentifier(current.provider, original.name)} ${quoteIdentifier(current.provider, nextName)} ${nextType}${draft.isNullable ? ' NULL' : ' NOT NULL'}${commentSql ? ` COMMENT ${sqlLiteral(commentSql)}` : ''}`);
      continue;
    }

    if (current.provider === 'sqlite') {
      if (typeChanged || nullableChanged || commentChanged) {
        throw new Error('SQLite 设计页当前只支持重命名字段。');
      }

      if (nameChanged) {
        statements.push(`ALTER TABLE ${tableName} RENAME COLUMN ${quoteIdentifier(current.provider, original.name)} TO ${quoteIdentifier(current.provider, nextName)}`);
      }
      continue;
    }

    const resolvedName = nameChanged ? nextName : original.name;
    if (nameChanged) {
      if (current.provider === 'sqlserver') {
        /* sp_rename 的第一个参数是一个点分隔的对象名字符串，必须在字符串内部使用 [] 引用标识符，
           否则包含 . 或 ] 的 schema/table/column 名会被错误解析。 */
        const bracketQuote = (v: string) => `[${v.replace(/\]/g, ']]')}]`;
        const fullColumnName = `${bracketQuote(current.schema ?? 'dbo')}.${bracketQuote(current.name)}.${bracketQuote(original.name)}`;
        statements.push(`EXEC sp_rename ${sqlUnicodeLiteral(fullColumnName)}, ${sqlUnicodeLiteral(nextName)}, N'COLUMN'`);
      }
      else {
        statements.push(`ALTER TABLE ${tableName} RENAME COLUMN ${quoteIdentifier(current.provider, original.name)} TO ${quoteIdentifier(current.provider, nextName)}`);
      }
    }

    if (typeChanged || nullableChanged) {
      if (current.provider === 'sqlserver') {
        statements.push(`ALTER TABLE ${tableName} ALTER COLUMN ${quoteIdentifier(current.provider, resolvedName)} ${nextType}${draft.isNullable ? ' NULL' : ' NOT NULL'}`);
      }
      else if (current.provider === 'postgresql') {
        if (typeChanged) {
          statements.push(`ALTER TABLE ${tableName} ALTER COLUMN ${quoteIdentifier(current.provider, resolvedName)} TYPE ${nextType}`);
        }

        if (nullableChanged) {
          statements.push(`ALTER TABLE ${tableName} ALTER COLUMN ${quoteIdentifier(current.provider, resolvedName)} ${draft.isNullable ? 'DROP' : 'SET'} NOT NULL`);
        }
      }
    }

    statements.push(...buildCommentStatements(current.provider, current.schema, current.name, resolvedName, original.comment, draft.comment));
  }

  /* 生成 DROP COLUMN 语句（放在末尾，先完成其它 ALTER 操作） */
  for (const droppedName of droppedColumns.value) {
    const original = current.columns.find((column) => column.name === droppedName);
    if (!original) {
      continue;
    }

    if (original.isPrimaryKey) {
      throw new Error(`字段 ${droppedName} 是主键，无法删除。`);
    }

    statements.push(`ALTER TABLE ${tableName} DROP COLUMN ${quoteIdentifier(current.provider, droppedName)}`);
  }

  return statements.join(';' + '\n');
}

async function saveDesign() {
  if (isReadOnlyObject.value) {
    return;
  }

  // eslint-disable-next-line no-useless-assignment
  let sql = '';
  try {
    sql = buildAlterSql();
    if (!sql.trim()) {
      return;
    }
  }
  catch (error) {
    store.showNotice('warning', error instanceof Error ? error.message : '表设计校验失败');
    return;
  }

  saving.value = true;
  try {
    await store.executeTableDesignSql(props.tab.tableKey, sql, '表结构已更新');
  }
  catch (error) {
    store.showNotice('warning', error instanceof Error ? error.message : '表设计保存失败');
  }
  finally {
    saving.value = false;
  }
}

function handleWindowKeydown(event: KeyboardEvent) {
  if (event.key !== 'F5') {
    return;
  }

  event.preventDefault();
  void store.ensureTableDesignLoaded(props.tab.tableKey, true);
}

onMounted(() => {
  window.addEventListener('keydown', handleWindowKeydown, true);
  window.addEventListener('click', closeDesignContextMenu, true);
  window.addEventListener('contextmenu', closeDesignContextMenu, true);
});

onBeforeUnmount(() => {
  window.removeEventListener('keydown', handleWindowKeydown, true);
  window.removeEventListener('click', closeDesignContextMenu, true);
  window.removeEventListener('contextmenu', closeDesignContextMenu, true);
});

watch(sectionTabs, (tabs) => {
  if (!tabs.length) {
    return;
  }

  if (!tabs.some((tab) => tab.key === selectedSection.value)) {
    focusSection(tabs[0]?.key ?? 'columns');
  }
}, { immediate: true });

</script>

<template>
  <NSpin :show="designStatus.loading || saving" class="table-design-spin">
    <div class="table-design-shell">
      <div class="table-design-header compact-panel">
        <h3 class="table-design-title">{{ tableLabel() }}</h3>
        <div class="table-design-actions">
          <NButton v-if="selectedSection === 'columns' && !isReadOnlyObject" size="small" tertiary @click="addColumn">新增字段</NButton>
          <NButton v-if="selectedSection === 'indexes' && !isReadOnlyObject" size="small" tertiary @click="openCreateIndexDialog">新建索引</NButton>
          <NButton size="small" tertiary @click="store.ensureTableDesignLoaded(props.tab.tableKey, true)">刷新</NButton>
          <NButton v-if="!isReadOnlyObject" size="small" type="primary" :disabled="!dirty || saving" @click="saveDesign">保存设计</NButton>
        </div>
      </div>

      <NAlert v-if="isReadOnlyObject" type="info" :show-icon="false" class="panel-inline-alert">
        当前对象是视图。这里提供对象结构浏览，不提供字段级修改。
      </NAlert>

      <div v-if="sectionTabs.length" class="table-design-subtabs compact-panel">
        <button
          v-for="item in sectionTabs"
          :key="item.key"
          type="button"
          class="table-design-subtab"
          :class="{ 'table-design-subtab-active': selectedSection === item.key }"
          @click="focusSection(item.key)"
        >
          <span>{{ item.label }}</span>
          <span class="table-design-subtab-count">{{ item.count }}</span>
        </button>
      </div>

      <NAlert v-if="designStatus.error" type="warning" :show-icon="false" class="panel-inline-alert">
        {{ designStatus.error }}
      </NAlert>

      <template v-if="design">
        <section v-if="selectedSection === 'columns'" class="table-design-main compact-panel">
          <div class="table-design-grid-wrap">
            <table class="table-design-grid">
              <colgroup>
                <col class="table-design-col-name">
                <col class="table-design-col-type">
                <col class="table-design-col-size">
                <col class="table-design-col-ratio">
                <col class="table-design-col-nullable">
                <col class="table-design-col-key">
                <col v-if="supportsColumnComment" class="table-design-col-comment">
                <col class="table-design-col-attrs">
              </colgroup>
              <thead>
                <tr>
                  <th>名称</th>
                  <th>类型</th>
                  <th>大小</th>
                  <th title="仅用于 decimal/numeric 之类带第二参数的类型，例如 decimal(18,2) 里的 2">比例</th>
                  <th>不是 null</th>
                  <th>键</th>
                  <th v-if="supportsColumnComment">注释</th>
                  <th>属性</th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="column in draftColumns"
                  :key="columnRowKey(column)"
                  :class="{ 'table-design-row-selected': selectedSection === 'columns' && selectedEntry === (column.originalName ?? column.name) }"
                  @click="focusSection('columns', column.originalName ?? column.name)"
                  @contextmenu.capture.prevent="openDesignContextMenu($event, 'column', column.originalName ?? column.name)"
                >
                  <td>
                    <NInput :value="column.name" size="small" :disabled="!canEditColumn(column)" @update:value="(value) => updateColumnName(column, value)" />
                  </td>
                  <td>
                    <div class="table-design-type-editor" @mousedown.stop @click.stop>
                      <NInput
                        v-model:value="column.typeInput"
                        size="small"
                        :disabled="!canEditColumn(column)"
                        placeholder="手动输入类型"
                        @blur="applyTypeInput(column, column.typeInput)"
                      >
                        <template #suffix>
                          <button type="button" class="table-design-input-suffix-button" :disabled="!canEditColumn(column)" @mousedown.stop @click.stop="toggleTypeMenu(column, $event)"><NIcon size="12"><ChevronDown /></NIcon></button>
                        </template>
                      </NInput>
                    </div>
                  </td>
                  <td>
                    <div v-if="showsPrimaryParameter(column)" class="table-design-dimension-cell">
                      <NInput :value="primaryParameterValue(column)" size="small" :disabled="!canEditColumn(column)" placeholder="大小" @update:value="(value) => setPrimaryParameterValue(column, value)" />
                    </div>
                    <span v-else class="table-design-dash">-</span>
                  </td>
                  <td>
                    <NInput v-if="showsSecondaryParameter(column)" :value="secondaryParameterValue(column)" size="small" :disabled="!canEditColumn(column)" placeholder="比例" @update:value="(value) => setSecondaryParameterValue(column, value)" />
                    <span v-else class="table-design-dash">-</span>
                  </td>
                  <td class="table-design-checkbox-cell">
                    <NCheckbox :checked="!column.isNullable" :disabled="!canEditColumn(column) || column.isPrimaryKey" @update:checked="(value) => { column.isNullable = !value }" />
                  </td>
                  <td>
                    <NTag v-if="column.isPrimaryKey" size="small" :bordered="false" type="warning">PK</NTag>
                    <span v-else class="panel-meta">-</span>
                  </td>
                  <td v-if="supportsColumnComment">
                    <div class="table-design-comment-editor" @mousedown.stop @click.stop>
                      <NInput v-model:value="column.comment" size="small" :disabled="!canEditColumn(column)" placeholder="列注释">
                        <template #suffix>
                          <button type="button" class="table-design-input-suffix-button" :disabled="!canEditColumn(column)" @mousedown.stop @click.stop="openCommentEditor(column, $event)"><NIcon size="12"><OverflowMenuHorizontal /></NIcon></button>
                        </template>
                      </NInput>
                    </div>
                  </td>
                  <td>
                    <NTag v-if="column.isNew" size="small" :bordered="false" type="success">新字段</NTag>
                    <NTag v-else-if="column.isAutoGenerated" size="small" :bordered="false">自动</NTag>
                    <NTag v-else-if="column.isComputed" size="small" :bordered="false">计算列</NTag>
                    <span v-else class="panel-meta">-</span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section v-else-if="selectedSection === 'indexes'" class="table-design-main compact-panel">
          <div class="table-design-object-wrap">
            <table v-if="design.indexes.length" class="table-design-object-grid">
              <thead>
                <tr>
                  <th>名称</th>
                  <th>列</th>
                  <th>唯一</th>
                  <th>主键</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="index in design.indexes" :key="index.name" :class="{ 'table-design-row-selected': selectedEntry === index.name }" @click="focusSection('indexes', index.name)" @contextmenu.capture.prevent="openDesignContextMenu($event, 'index', index.name)">
                  <td>{{ index.name }}</td>
                  <td>{{ index.columns.join(', ') }}</td>
                  <td>{{ index.isUnique ? '是' : '-' }}</td>
                  <td>{{ index.isPrimaryKey ? '是' : '-' }}</td>
                </tr>
              </tbody>
            </table>
            <NEmpty v-else size="small" :description="`当前${objectLabel}没有索引`" />
          </div>
        </section>

        <section v-else-if="selectedSection === 'foreignKeys'" class="table-design-main compact-panel">
          <div class="table-design-object-wrap">
            <table v-if="design.foreignKeys.length" class="table-design-object-grid">
              <thead>
                <tr>
                  <th>源字段</th>
                  <th>目标列</th>
                  <th>逻辑关系</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="foreignKey in design.foreignKeys" :key="`${foreignKey.sourceColumn}:${foreignKey.targetColumn}`" :class="{ 'table-design-row-selected': selectedEntry === foreignKey.sourceColumn }" @click="focusSection('foreignKeys', foreignKey.sourceColumn)">
                  <td>{{ foreignKey.sourceColumn }}</td>
                  <td>{{ foreignKey.targetColumn }}</td>
                  <td>{{ foreignKey.logical ? '是' : '-' }}</td>
                </tr>
              </tbody>
            </table>
            <NEmpty v-else size="small" description="当前表没有外键" />
          </div>
        </section>

        <section v-else-if="selectedSection === 'triggers'" class="table-design-main compact-panel">
          <div class="table-design-object-wrap">
            <table v-if="design.triggers.length" class="table-design-object-grid">
              <thead>
                <tr>
                  <th>名称</th>
                  <th>时机</th>
                  <th>事件</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="trigger in design.triggers" :key="trigger.name" :class="{ 'table-design-row-selected': selectedEntry === trigger.name }" @click="focusSection('triggers', trigger.name)">
                  <td>{{ trigger.name }}</td>
                  <td>{{ trigger.timing || '-' }}</td>
                  <td>{{ trigger.event || '-' }}</td>
                </tr>
              </tbody>
            </table>
            <NEmpty v-else size="small" :description="`当前${objectLabel}没有触发器`" />
          </div>
        </section>

        <section v-else class="table-design-main compact-panel">
          <div class="table-design-object-wrap">
            <table v-if="design.statistics.length" class="table-design-object-grid">
              <thead>
                <tr>
                  <th>名称</th>
                  <th>列</th>
                  <th>来源</th>
                  <th>过滤条件</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="statistic in design.statistics" :key="statistic.name" :class="{ 'table-design-row-selected': selectedEntry === statistic.name }" @click="focusSection('statistics', statistic.name)">
                  <td>{{ statistic.name }}</td>
                  <td>{{ statistic.columns.join(', ') || '-' }}</td>
                  <td>{{ statistic.isAutoCreated ? '自动' : statistic.isUserCreated ? '用户' : '-' }}</td>
                  <td>{{ statistic.filterDefinition || '-' }}</td>
                </tr>
              </tbody>
            </table>
            <NEmpty v-else size="small" :description="`当前${objectLabel}没有统计信息`" />
          </div>
        </section>
      </template>
    </div>
  </NSpin>

  <Teleport to="body">
    <NModal
      :show="createIndexVisible"
      preset="card"
      style="width: min(460px, 92vw)"
      title="新建索引"
      @update:show="(show) => { if (!show) closeCreateIndexDialog() }"
    >
      <div class="connection-dialog-form">
        <NInput v-model:value="createIndexName" placeholder="索引名称，例如 IX_Table_Column" />
        <NCheckbox v-model:checked="createIndexUnique">唯一索引</NCheckbox>
        <NSelect v-model:value="createIndexColumns" multiple filterable :options="indexColumnOptions" placeholder="选择索引列" />
        <NAlert v-if="createIndexError" type="warning" :show-icon="false">{{ createIndexError }}</NAlert>
        <div class="connection-dialog-actions">
          <NButton tertiary :disabled="createIndexLoading" @click="closeCreateIndexDialog">取消</NButton>
          <NButton type="primary" :loading="createIndexLoading" @click="submitCreateIndex">创建</NButton>
        </div>
      </div>
    </NModal>

    <div
      v-if="designContextMenu"
      class="table-design-context-menu"
      :style="{ left: `${designContextMenu.x}px`, top: `${designContextMenu.y}px` }"
      @click.stop
      @mousedown.stop
      @contextmenu.prevent
    >
      <button type="button" class="table-design-context-menu-item table-design-context-menu-item-danger" @click="handleContextDelete()">
        {{ designContextMenu.kind === 'column' ? '删除字段' : '删除索引' }}
      </button>
    </div>

    <div
      v-if="typeMenuRowKey && typeMenuPosition"
      class="table-design-type-overlay"
      :style="{
        top: `${typeMenuPosition.top}px`,
        left: `${typeMenuPosition.left}px`,
        width: `${typeMenuPosition.width}px`,
      }"
      @mousedown.stop
      @click.stop
    >
      <div class="table-design-type-popover" :style="{ height: `${typeMenuPosition.height}px` }">
        <div class="table-design-type-scrollbar">
          <div class="table-design-type-list">
            <button
              v-for="option in providerTypeOptions"
              :key="option.value"
              type="button"
              class="table-design-type-option"
              :class="{ 'table-design-type-option-active': isActiveTypeOption(option.value) }"
              @click.stop="activeTypeMenuColumn() && selectTypeFromMenu(activeTypeMenuColumn()!, option.value)"
            >
              {{ option.label }}
            </button>
          </div>
        </div>
      </div>
    </div>

    <div
      v-if="supportsColumnComment && commentEditorVisible && commentEditorPosition"
      class="table-design-comment-overlay"
      :style="{
        top: `${commentEditorPosition.top}px`,
        left: `${commentEditorPosition.left}px`,
        width: `${commentEditorPosition.width}px`,
      }"
      @mousedown.stop
      @click.stop
    >
      <div class="table-design-comment-flyout">
        <textarea
          ref="commentEditorTextarea"
          v-model="commentEditorDraft"
          class="table-design-comment-textarea"
          placeholder="输入字段注释"
        />
        <div class="table-design-comment-flyout-actions">
          <NButton size="small" tertiary @click="closeCommentEditor">取消</NButton>
          <NButton size="small" type="primary" @click="applyCommentEditor">确定</NButton>
        </div>
      </div>
    </div>

  </Teleport>
</template>

<style scoped lang="scss">
.table-design-spin {
  display: flex;
  flex-direction: column;
  min-height: 0;
  height: 100%;

  :deep(.n-spin-content) {
    display: flex;
    flex-direction: column;
    min-height: 0;
    height: 100%;
  }
}

.table-design-shell {
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-height: 0;
  height: 100%;
}

.table-design-header,
.table-design-actions,
.table-design-object-list-header,
.table-design-comment-flyout-actions {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
}

.table-design-header {
  padding: 5px 8px;
}

.table-design-title {
  margin: 0;
  font-size: 16px;
  line-height: 1.1;
}

.table-design-subtabs {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 4px 6px;
  overflow-x: auto;
}

.table-design-subtab {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 5px 10px;
  border: 1px solid rgba(148, 163, 184, 0.18);
  border-radius: 999px;
  background: rgba(248, 250, 252, 0.96);
  color: #334155;
  font-size: 11px;
  font-weight: 700;
  cursor: pointer;
}

.table-design-subtab-active {
  background: #ffffff;
  border-color: rgba(37, 99, 235, 0.32);
  color: #1d4ed8;
}

.table-design-subtab-count {
  color: #64748b;
  font-size: 10px;
}

.table-design-context-menu {
  position: fixed;
  z-index: 2600;
  min-width: 156px;
  padding: 4px;
  border: 1px solid rgba(148, 163, 184, 0.28);
  border-radius: var(--radius-md);
  background: rgba(255, 255, 255, 0.98);
  box-shadow: 0 16px 40px rgba(15, 23, 42, 0.16);
  transform-origin: top left;
  animation: context-menu-enter 140ms ease;
}

.table-design-context-menu-item {
  width: 100%;
  padding: 6px 10px;
  border: 0;
  border-radius: var(--radius-sm);
  background: transparent;
  font-size: 12px;
  line-height: 1.25;
  text-align: left;
  cursor: pointer;

  &:hover {
    background: rgba(241, 245, 249, 0.96);
  }

  &-danger {
    color: #b91c1c;
  }
}

.table-design-main {
  display: flex;
  flex-direction: column;
  gap: 6px;
  min-height: 0;
  padding: 5px 7px;
  flex: 1 1 auto;
}

.table-design-grid-wrap,
.table-design-object-wrap {
  min-height: 0;
  overflow: auto;
}

.table-design-grid {
  width: 100%;
  border-collapse: collapse;
  table-layout: fixed;
}

.table-design-object-grid {
  width: 100%;
  border-collapse: collapse;
}

.table-design-col-name {
  width: 170px;
}

.table-design-col-type {
  width: 220px;
}

.table-design-col-size {
  width: 116px;
}

.table-design-col-ratio {
  width: 86px;
}

.table-design-col-nullable {
  width: 84px;
}

.table-design-col-key {
  width: 60px;
}

.table-design-col-comment {
  width: 280px;
}

.table-design-col-attrs {
  width: 96px;
}

.table-design-col-actions {
  width: 36px;
}

.table-design-action-cell {
  text-align: center;
}

.table-design-delete-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 20px;
  height: 20px;
  padding: 0;
  border: none;
  border-radius: 4px;
  background: transparent;
  color: #94a3b8;
  font-size: 12px;
  cursor: pointer;
  transition: background 0.15s, color 0.15s;

  &:hover {
    background: rgba(239, 68, 68, 0.12);
    color: #ef4444;
  }

  &:disabled {
    cursor: not-allowed;
    opacity: 0.4;
    background: transparent;
    color: #94a3b8;
  }
}

.table-design-grid th,
.table-design-grid td,
.table-design-object-grid th,
.table-design-object-grid td {
  padding: 3px 5px;
  border-bottom: 1px solid rgba(226, 232, 240, 0.85);
  text-align: left;
  vertical-align: middle;
  font-size: 11px;
}

.table-design-grid th,
.table-design-object-grid th {
  position: sticky;
  top: 0;
  background: #f8fafc;
  z-index: 1;
  font-size: 12px;
  font-weight: 800;
  color: #334155;
}

.table-design-row-selected {
  background: rgba(239, 246, 255, 0.78);
}

.table-design-checkbox-cell {
  text-align: center;
}

.table-design-type-editor,
.table-design-comment-editor,
.table-design-dimension-cell {
  display: flex;
  align-items: center;
  gap: 0;
}

.table-design-type-editor {
  width: 100%;
}

.table-design-type-editor :deep(.n-input),
.table-design-type-editor :deep(.n-input-wrapper) {
  width: 100%;
}

.table-design-comment-overlay {
  position: fixed;
  z-index: 2500;
}

.table-design-comment-flyout {
  width: min(280px, calc(100vw - 28px));
  display: grid;
  gap: 4px;
  padding: 4px;
  border: 1px solid rgba(148, 163, 184, 0.22);
  border-radius: 8px;
  background: #ffffff;
  box-shadow: 0 18px 34px rgba(15, 23, 42, 0.16);

  :deep(.n-input-wrapper),
  :deep(.n-input__textarea) {
    padding: 0;
    border-radius: 6px !important;
  }

  :deep(textarea) {
    padding: 6px 8px !important;
    line-height: 1.35;
  }

  &-actions {
    justify-content: flex-end;
    gap: 4px;
  }
}

.table-design-comment-textarea {
  width: 100%;
  min-height: 112px;
  max-height: min(240px, calc(100vh - 120px));
  box-sizing: border-box;
  padding: 7px 9px;
  border: 1px solid rgba(148, 163, 184, 0.24);
  border-radius: 6px;
  outline: none;
  resize: vertical;
  color: #0f172a;
  font: inherit;
  font-size: 11px;
  line-height: 1.4;
  background: #ffffff;
}

.table-design-comment-textarea:focus {
  border-color: rgba(34, 197, 94, 0.58);
  box-shadow: 0 0 0 2px rgba(34, 197, 94, 0.12);
}

.table-design-comment-flyout-actions {
  justify-content: flex-end;
  gap: 4px;
}

.table-design-type-overlay {
  position: fixed;
  z-index: 2500;
  animation: table-design-overlay-enter 120ms ease;
}

.table-design-type-popover {
  width: 100%;
  padding: 0;
  border: 1px solid rgba(148, 163, 184, 0.18);
  border-radius: 7px;
  background: #ffffff;
  box-shadow: 0 16px 30px rgba(15, 23, 42, 0.14);
  overflow: hidden;
}

.table-design-type-scrollbar {
  height: 100%;
  overflow-y: auto;
  overflow-x: hidden;
}

.table-design-type-list {
  display: grid;
  gap: 0;
  padding: 0;
}

.table-design-type-option {
  width: 100%;
  padding: 5px 8px;
  border: 0;
  border-radius: 0;
  background: transparent;
  text-align: left;
  cursor: pointer;
  font-size: 10px;
  line-height: 1.15;
}

.table-design-type-option:hover {
  background: rgba(239, 246, 255, 0.92);
}

.table-design-type-option-active {
  background: rgba(219, 234, 254, 0.9);
  color: #1d4ed8;
  font-weight: 700;
}

.table-design-input-suffix-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 18px;
  height: 18px;
  padding: 0;
  border: 0;
  border-radius: 3px;
  background: transparent;
  color: #94a3b8;
  font-size: 10px;
  font-weight: 800;
  line-height: 1;
  cursor: pointer;
  transition: color 100ms ease, background 100ms ease;
}

.table-design-input-suffix-button:hover {
  color: #334155;
  background: rgba(241, 245, 249, 0.92);
}

.table-design-input-suffix-button:disabled {
  cursor: not-allowed;
  opacity: 0.4;
}

@keyframes table-design-overlay-enter {
  from {
    opacity: 0;
    transform: translateY(-4px) scaleY(0.97);
  }

  to {
    opacity: 1;
    transform: translateY(0) scaleY(1);
  }
}

.table-design-dash,
.table-design-footnote {
  color: #64748b;
  font-size: 10px;
}

.table-design-footnote {
  padding: 0 2px;
}

@media (max-width: 980px) {
  .table-design-col-comment {
    width: 220px;
  }

  .table-design-col-type {
    width: 190px;
  }
}
</style>