namespace DatabaseViewer.Api.Contracts;

public sealed record BootstrapResponse(IReadOnlyList<ConnectionNodeDto> Connections);

public sealed record ConnectionNodeDto(
    Guid Id,
    string Name,
    string Provider,
    string Host,
    int? Port,
    string Authentication,
    string Accent,
    string? Error,
    IReadOnlyList<DatabaseNodeDto> Databases);

public sealed record DatabaseNodeDto(
    string Name,
    IReadOnlyList<TableNodeDto> Tables,
    IReadOnlyList<TableNodeDto> Views,
    IReadOnlyList<SynonymNodeDto> Synonyms,
    IReadOnlyList<SequenceNodeDto> Sequences,
    IReadOnlyList<RuleNodeDto> Rules,
    IReadOnlyList<DefaultNodeDto> Defaults,
    IReadOnlyList<UserDefinedTypeNodeDto> UserDefinedTypes,
    IReadOnlyList<RoutineNodeDto> Routines);

public sealed record DatabaseGraphNodeDto(
    string TableKey,
    string Title,
    int? RowCount,
    bool IsJunction,
    string? Comment,
    IReadOnlyList<DatabaseGraphColumnDto> Columns);

public sealed record DatabaseGraphColumnDto(
    string Name,
    string Type,
    string DisplayType,
    bool IsNullable,
    bool IsPrimaryKey,
    bool IsForeignKey);

public sealed record DatabaseGraphEdgeDto(
    string SourceTableKey,
    string TargetTableKey,
    string RelationType,
    string Label,
    bool Logical,
    string? ViaTableKey,
    string SourceColumn,
    string TargetColumn);

public sealed record DatabaseGraphResponse(
    Guid ConnectionId,
    string Database,
    IReadOnlyList<DatabaseGraphNodeDto> Nodes,
    IReadOnlyList<DatabaseGraphEdgeDto> Edges);

public sealed record TableNodeDto(string Key, string Database, string? Schema, string Name, string ObjectType, string? Comment, int? RowCount);

public sealed record SynonymNodeDto(string Database, string? Schema, string Name, string BaseObjectName);

public sealed record SequenceNodeDto(string Database, string? Schema, string Name, string DataType, string StartValue, string IncrementValue);

public sealed record RuleNodeDto(string Database, string? Schema, string Name, string? Definition);

public sealed record DefaultNodeDto(string Database, string? Schema, string Name, string? Definition);

public sealed record UserDefinedTypeNodeDto(string Database, string? Schema, string Name, string BaseTypeName, bool IsTableType);

public sealed record RoutineNodeDto(string? Schema, string Name, string RoutineType, IReadOnlyList<RoutineParameterDto> Parameters);

/// <summary>
/// 存储过程或函数的参数。
/// </summary>
public sealed record RoutineParameterDto(string Name, string DataType, string Direction, string? DefaultValue);

public sealed record ColumnDto(
    string Name,
    string Type,
    bool IsPrimaryKey,
    bool IsNullable,
    bool IsAutoGenerated,
    bool IsComputed,
    int? MaxLength,
    string? Comment,
    int? NumericPrecision,
    int? NumericScale);

public sealed record ForeignKeyDto(string SourceColumn, string TargetTableKey, string TargetColumn, bool Logical);

public sealed record TableIndexDto(string Name, bool IsPrimaryKey, bool IsUnique, IReadOnlyList<string> Columns);

public sealed record TableTriggerDto(string Name, string? Timing, string? Event);

public sealed record TableStatisticDto(
    string Name,
    bool IsAutoCreated,
    bool IsUserCreated,
    bool NoRecompute,
    string? FilterDefinition,
    IReadOnlyList<string> Columns);

public sealed record TableDesignResponse(
    string TableKey,
    Guid ConnectionId,
    string Database,
    string Provider,
    string ObjectType,
    string? Schema,
    string Name,
    string? Comment,
    IReadOnlyList<ColumnDto> Columns,
    IReadOnlyList<ForeignKeyDto> ForeignKeys,
    IReadOnlyList<TableIndexDto> Indexes,
    IReadOnlyList<TableTriggerDto> Triggers,
    IReadOnlyList<TableStatisticDto> Statistics);

public sealed record CatalogObjectPropertyDto(string Label, string? Value);

public sealed record CatalogObjectDetailResponse(
    Guid ConnectionId,
    string Database,
    string Provider,
    string ObjectType,
    string? Schema,
    string Name,
    string Title,
    string? Summary,
    string? Definition,
    IReadOnlyList<CatalogObjectPropertyDto> Properties);

public sealed record TablePageResponse(
    string TableKey,
    string Database,
    string? Schema,
    string Name,
    string? Comment,
    int? RowCount,
    IReadOnlyList<string> PrimaryKeys,
    IReadOnlyList<ColumnDto> Columns,
    IReadOnlyList<ForeignKeyDto> ForeignKeys,
    IReadOnlyList<Dictionary<string, object?>> Rows,
    bool HasMoreRows);

public sealed record TableSearchResponse(
    string TableKey,
    string Query,
    IReadOnlyList<string> Columns,
    IReadOnlyList<Dictionary<string, object?>> Rows,
    int TotalMatches,
    bool HasMoreRows);

public sealed record CellContentResponse(
    string TableKey,
    string RowKey,
    string ColumnName,
    string Kind,
    string MimeType,
    string SuggestedFileName,
    int SizeBytes,
    string? TextContent,
    string? Base64Data);

public sealed record ReverseReferenceRowDto(string RowKey, Dictionary<string, object?> Values);

public sealed record ReverseReferenceGroupDto(string SourceTableKey, string RelationLabel, IReadOnlyList<ReverseReferenceRowDto> Rows);

public sealed record RecordResponse(
    string TableKey,
    string RowKey,
    Dictionary<string, object?> Row,
    IReadOnlyList<string> PrimaryKeys,
    IReadOnlyList<ColumnDto> Columns,
    IReadOnlyList<ForeignKeyDto> ForeignKeys,
    IReadOnlyList<ReverseReferenceGroupDto> ReverseReferences);

public sealed record ForeignKeyTargetResponse(string TargetTableKey, string TargetRowKey, string SourceLabel);

public sealed record SqlExecutionRequest(Guid ConnectionId, string Database, string Sql);

public sealed record RoutineSourceRequest(Guid ConnectionId, string Database, string? Schema, string Name, string RoutineType);

public sealed record RoutineSourceResponse(string? Source);

public sealed record CreateConnectionRequest(
    string Name,
    string Provider,
    string Authentication,
    string Host,
    int? Port,
    string? Username,
    string? Password,
    bool TrustServerCertificate);

public sealed record ConnectionConfigResponse(
    Guid Id,
    string Name,
    string Provider,
    string Authentication,
    string Host,
    int? Port,
    string? Username,
    bool TrustServerCertificate);

public sealed record TestConnectionRequest(
    Guid? ConnectionId,
    string Name,
    string Provider,
    string Authentication,
    string Host,
    int? Port,
    string? Username,
    string? Password,
    bool TrustServerCertificate);

public sealed record SqlResultColumnDto(string Name, string Type);

public sealed record SqlResultSetDto(
    string Name,
    IReadOnlyList<SqlResultColumnDto> Columns,
    IReadOnlyList<Dictionary<string, object?>> Rows,
    int RowCount,
    bool Truncated);

public sealed record SqlExecutionResponse(
    Guid ConnectionId,
    string Database,
    string ExecutedSql,
    int? AffectedRows,
    long ElapsedMs,
    IReadOnlyList<SqlResultSetDto> ResultSets);

public sealed record SqlContextTableDto(
    string Name,
    string? Schema,
    string QualifiedName,
    IReadOnlyList<string> Columns);

public sealed record SqlContextResponse(
    Guid ConnectionId,
    string Database,
    string Provider,
    IReadOnlyList<SqlContextTableDto> Tables);

public sealed record TableCellUpdateRequest(
    string TableKey,
    string RowKey,
    string ColumnName,
    string ValueKind,
    string? TextValue,
    string? Base64Value,
    bool SetNull);

public sealed record TableCellUpdateResponse(
    string TableKey,
    string PreviousRowKey,
    string RowKey,
    Dictionary<string, object?> Row);

public sealed record TableRowWriteValueRequest(
    string ColumnName,
    string ValueKind,
    string? TextValue,
    string? Base64Value,
    bool SetNull);

public sealed record TableRowInsertRequest(
    string TableKey,
    IReadOnlyList<TableRowWriteValueRequest> Values);

public sealed record TableRowInsertResponse(
    string TableKey,
    string? RowKey,
    Dictionary<string, object?>? Row);

public sealed record TableRowDeleteRequest(
    string TableKey,
    string RowKey);